insert into bj_groups (group_name,group_id) VALUES('серьги Люкс',1418);
insert into bj_groups (group_name,group_id) VALUES('кольца Люкс',1419);
insert into bj_groups (group_name,group_id) VALUES('кресты декоративные',1420);
insert into bj_groups (group_name,group_id) VALUES('браслеты кожаные',1421);
insert into bj_groups (group_name,group_id) VALUES('серьги',1422);
insert into bj_groups (group_name,group_id) VALUES('кольца',1423);
insert into bj_groups (group_name,group_id) VALUES('колье, цепи',1424);
insert into bj_groups (group_name,group_id) VALUES('браслеты',1425);
insert into bj_groups (group_name,group_id) VALUES('браслеты на ногу',1426);
insert into bj_groups (group_name,group_id) VALUES('броши',1427);
insert into bj_groups (group_name,group_id) VALUES('колье, подвески Люкс',1428);
insert into bj_groups (group_name,group_id) VALUES('коллекция "Дерзская"',1430);

insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26442,'КЛП052/Б-Люкс','Клипсы "РОБЕРТО", матирование, фианиты, белое золото, клипса/гвоздик','klipsy_roberto_matirovanie_fianity_beloe_zoloto_klipsagvozdik',69200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26392,'СР0004/Б-Люкс','Серьги "Крабики" с фианитами и синт.топазами, жемчугом, эмалью, белые, гвоздик, Люкс','sergi_krabiki_s_fianitami_i_sint.topazami_zhemchugom_jemalyu_belye_gvozdik_lyuks',91200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26791,'СРЛ188/Б-ЦФ-Люкс','Серьги-гвоздики крупные С ОВАЛЬНЫМИ ПОДВЕСАМИ, цветные фианиты, металл: белый, Люкс','sergi_gvozdiki_krupnye_s_ovalnymi_podvesami_cvetnye_fianity_metall_belyjj_lyuks',155600);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26511,'СРЛ055/Б-Люкс','Серьги длинные вечерние МОДЕРН с иск. изумрудами и сапфирами, гвоздик','sergi_dlinnye_vechernie_modern_s_isk._izumrudami_i_sapfirami_gvozdik',161800);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26709,'К005-Б-17','Кольцо с разноцветными камнями, белое,17 размер, Люкс','kolco_s_raznocvetnymi_kamnyami_beloe17_razmer_lyuks',13800);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26702,'К001-Б-18','Кольцо с фианитами, синт.сапфиром, белое, 18 размер, Люкс','kolco_s_fianitami_sint.sapfirom_beloe_18_razmer_lyuks',35600);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26859,'КЛ051-Б-ПРБ-б/р','Кольцо раздвижное ПТИЧКА С ИСК. ПАРАИБОЙ с фианитами и иск сапфирами, цвет:белый, без размера, Люкс','kolco_razdvizhnoe_ptichka_s_isk._paraibojj_s_fianitami_i_isk_sapfirami_cvetbelyjj_bez_razmera_lyuks',141500);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26701,'КРЕСТ-017/Б-ЛЮКС','Крест декоративный большой С ИСК.ИЗУМРУДАМИ И САПФИРАМИ, ФИАНИТАМИ, металл: белый','krest_dekorativnyjj_bolshojj_s_isk.izumrudami_i_sapfirami_fianitami_metall_belyjj',55000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26553,'КРЕСТ-001/Б-ЛЮКС','Крест декоративный с фианитами, металл: белый, 45 см, Люкс','krest_dekorativnyjj_s_fianitami_metall_belyjj_45_sm_lyuks',92600);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26578,'КРЕСТ-016/Б-ЛЮКС','Крест декоративный С ИСК, РУБИНАМИ И ФИАНИТАМИ, металл: белый','krest_dekorativnyjj_s_isk_rubinami_i_fianitami_metall_belyjj',119200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27493,'БК010-Т.КРЧ-АССОРТИ-б/р','Браслет т. коричневый (АССОРТИ) кожаный, плетения разные, без размера','braslet_t._korichnevyjj_assorti_kozhanyjj_pleteniya_raznye_bez_razmera',5400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27472,'БК002-БЖ/Ж-19','Браслет широкий сборный бежевый , кожа, шнуры, стразы, металл: желтый, замок магнитный, 19 см','braslet_shirokijj_sbornyjj_bezhevyjj__kozha_shnury_strazy_metall_zheltyjj_zamok_magnitnyjj_19_sm',40000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27513,'БК020-ТКРЧ-22','Браслет сборный т.коричневый с ЗОЛОТИСТЫМИ НАКЛАДКАМИ кожа, металл: желтый, замок магнитный,22 см','braslet_sbornyjj_t.korichnevyjj_s_zolotistymi_nakladkami_kozha_metall_zheltyjj_zamok_magnitnyjj22_sm',58400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26948,'СР0087/Ж-S','Серьги "Полукольца" широкие, малые, желтые, гвоздик','sergi_polukolca_shirokie_malye_zheltye_gvozdik',4200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26844,'КП-002-3/Р','Комплект - серьги, колье, кольцо "СЕРДЕЧКИ ОБЪЕМНЫЕ", металл: розово-жёлтый','komplekt___sergi_kole_kolco_serdechki_obemnye_metall_rozovo_zhjoltyjj',12400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27147,'СР0185/Б','Серьги - большие конго СС, фианиты, цвет металла белый','sergi___bolshie_kongo_ss_fianity_cvet_metalla_belyjj',46200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27666,'КО057-Р-20','Кольцо обручальное с фианитом, розовое, размер 20','kolco_obruchalnoe_s_fianitom_rozovoe_razmer_20',6200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27516,'КО027-Б-15','Кольцо обручальное с квадратными фианитами, ДОРОЖКА, белое, размер 15','kolco_obruchalnoe_s_kvadratnymi_fianitami_dorozhka_beloe_razmer_15',9000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27517,'КО027-Б-16','Кольцо обручальное с квадратными фианитами, ДОРОЖКА, белое, размер 16','kolco_obruchalnoe_s_kvadratnymi_fianitami_dorozhka_beloe_razmer_16',9000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27527,'КО027-Р-20','Кольцо обручальное с квадратными фианитами, ДОРОЖКА, розовое , размер 20','kolco_obruchalnoe_s_kvadratnymi_fianitami_dorozhka_rozovoe__razmer_20',100000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27316,'КОЛЬЕ-005/Ж','Колье - цепочка с жемчугом, металл: желтый, 45 см','kole___cepochka_s_zhemchugom_metall_zheltyjj_45_sm',4800);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27302,'КОЛЬЕ-001-2/Б','Колье - 2 цепи с подвесм "КОРОЛЕВА" металл: белый, 45 см','kole___2_cepi_s_podvesm_koroleva_metall_belyjj_45_sm',11300);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27412,'КОЛЬЕ-047-5/Б','Колье - чокер/5, с ФИАНИТАМИ, металл: белый, 40 см','kole___choker5_s_fianitami_metall_belyjj_40_sm',57400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27574,'БРТ018/Б','Браслет - подвижный с жемчугом и бусинами, металл: белый, карабин','braslet___podvizhnyjj_s_zhemchugom_i_businami_metall_belyjj_karabin',6400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27559,'БРТ001/Ж','Браслет - скоба с большими ажурными шарми и иск.жемчугом , металл: желтый, без замка, шарнир','braslet___skoba_s_bolshimi_azhurnymi_sharmi_i_isk.zhemchugom__metall_zheltyjj_bez_zamka_sharnir',21000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27599,'БРТ035/Р','Браслет - обруч "БАБОЧКИ" , металл: розовый, без замка, шарнир','braslet___obruch_babochki__metall_rozovyjj_bez_zamka_sharnir',58400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27554,'БН001/Ж','Браслет - двойная цепочка с круглой подвеской с пропилами, металл: желтый, карабин, 30+5 см','braslet___dvojjnaya_cepochka_s_kruglojj_podveskojj_s_propilami_metall_zheltyjj_karabin_305_sm',9400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27548,'БН003/Р','Браслет - цепочка с круглыми вставками (монетками) и БУБЕНЦАМИ, металл: розовый, карабин, 30+5 см','braslet___cepochka_s_kruglymi_vstavkami_monetkami_i_bubencami_metall_rozovyjj_karabin_305_sm',15200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27557,'БН006/Р','Браслет - двойная цепочка со ЗВЕЗДОЧКАМИ И ШАРИКАМИ, металл: розовый, карабин, 30+5 см','braslet___dvojjnaya_cepochka_so_zvezdochkami_i_sharikami_metall_rozovyjj_karabin_305_sm',17400);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26396,'Б001-Б-Ж','Брошь Бантик малый с фианитами, крепление - булавка, цвет золото желтое','brosh_bantik_malyjj_s_fianitami_kreplenie___bulavka_cvet_zoloto_zheltoe',3600);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26412,'Б023-Ж-1','Брошь ПАНДА С БАМБУКОМ, ФИАНИТЫ, ЭМАЛЬ - булавка, цвет золото желтое','brosh_panda_s_bambukom_fianity_jemal___bulavka_cvet_zoloto_zheltoe',12500);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26432,'Б021-Ж','Брошь ВОРОБЕЙ С ЦВЕТНЫМИ ФИАНИТАМИ НА ВЕТОЧКЕ - булавка, цвет золото желтое','brosh_vorobejj_s_cvetnymi_fianitami_na_vetochke___bulavka_cvet_zoloto_zheltoe',13100);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26402,'Б029-Ж','Брошь С ТЕКСТИЛЬНЫМИ ЦВЕТАМИ И ЗОЛОТИСТЫМИ ЛИСТЬЯМИ, булавка','brosh_s_tekstilnymi_cvetami_i_zolotistymi_listyami_bulavka',35000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27717,'КОЛЬЕ-068/Б','Колье - цепь тонкая с подвеской КРЕСТ И ВОЛНА,металл:белый, карабин, 40+5 см','kole___cep_tonkaya_s_podveskojj_krest_i_volnametallbelyjj_karabin_405_sm',17800);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27684,'БРТ047/Р','Браслет широкий вечерний "ЛЕТО" с цветными фианитами, металл:розовый, 20 см','braslet_shirokijj_vechernijj_leto_s_cvetnymi_fianitami_metallrozovyjj_20_sm',69900);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(27775,'ГАРН002/Б/-РУБИ-3-б/р','Гарнитур вечерний "БАНТЫ" с иск. рубином и фианитами, серьги-гвозди, кольцо б/р, подвеска с цепью','garnitur_vechernijj_banty_s_isk._rubinom_i_fianitami_sergi_gvozdi_kolco_br_podveska_s_cepyu',476200);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26651,'Д-КОЛЬЦО-09/Б-17','Кольцо узкое ВОЛНА, металл: белый, размер 17','kolco_uzkoe_volna_metall_belyjj_razmer_17',13000);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26592,'Д-БРАСЛЕТ-11/Б','Браслет - обруч средний ВОЛНА, металл: белый, шарнир','braslet___obruch_srednijj_volna_metall_belyjj_sharnir',51700);
insert into public.bj_products (inner_id,articul,product_name,product_alias,price) values(26623,'Д-КОЛЬЕ-03/Б','Колье - чокер - ДВОЙНАЯ СКОБА массивное изделие, металл: белый, шарнир 40 см','kole___choker___dvojjnaya_skoba_massivnoe_izdelie_metall_belyjj_sharnir_40_sm',123800);

insert into public.products_groups (product_id,group_id) values(26442,1418);
insert into public.products_groups (product_id,group_id) values(26392,1418);
insert into public.products_groups (product_id,group_id) values(26791,1418);
insert into public.products_groups (product_id,group_id) values(26511,1418);
insert into public.products_groups (product_id,group_id) values(26709,1419);
insert into public.products_groups (product_id,group_id) values(26702,1419);
insert into public.products_groups (product_id,group_id) values(26859,1419);
insert into public.products_groups (product_id,group_id) values(26701,1420);
insert into public.products_groups (product_id,group_id) values(26553,1420);
insert into public.products_groups (product_id,group_id) values(26578,1420);
insert into public.products_groups (product_id,group_id) values(27493,1421);
insert into public.products_groups (product_id,group_id) values(27472,1421);
insert into public.products_groups (product_id,group_id) values(27513,1421);
insert into public.products_groups (product_id,group_id) values(26948,1422);
insert into public.products_groups (product_id,group_id) values(26844,1422);
insert into public.products_groups (product_id,group_id) values(27147,1422);
insert into public.products_groups (product_id,group_id) values(27666,1423);
insert into public.products_groups (product_id,group_id) values(27516,1423);
insert into public.products_groups (product_id,group_id) values(27517,1423);
insert into public.products_groups (product_id,group_id) values(27527,1423);
insert into public.products_groups (product_id,group_id) values(27316,1424);
insert into public.products_groups (product_id,group_id) values(27302,1424);
insert into public.products_groups (product_id,group_id) values(27412,1424);
insert into public.products_groups (product_id,group_id) values(27574,1425);
insert into public.products_groups (product_id,group_id) values(27559,1425);
insert into public.products_groups (product_id,group_id) values(27599,1425);
insert into public.products_groups (product_id,group_id) values(27554,1426);
insert into public.products_groups (product_id,group_id) values(27548,1426);
insert into public.products_groups (product_id,group_id) values(27557,1426);
insert into public.products_groups (product_id,group_id) values(26396,1427);
insert into public.products_groups (product_id,group_id) values(26412,1427);
insert into public.products_groups (product_id,group_id) values(26432,1427);
insert into public.products_groups (product_id,group_id) values(26402,1427);
insert into public.products_groups (product_id,group_id) values(27717,1428);
insert into public.products_groups (product_id,group_id) values(27684,1428);
insert into public.products_groups (product_id,group_id) values(27775,1428);
insert into public.products_groups (product_id,group_id) values(26651,1430);
insert into public.products_groups (product_id,group_id) values(26592,1430);
insert into public.products_groups (product_id,group_id) values(26623,1430);
